config/routes.rb
Invoiceapp::Application.routes.draw do

  get "welcome/index"

   
  resources :invoices do 
   resource :form_detail
   resource :service
   resources :my_details
   resource :bank_detail
   resources :clients
end 

      
   
  

  root 'welcome#index'

  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	
	has_one :form_detail
	has_many :services, dependent: :destroy

	belongs_to :client, dependent: :destroy
	belongs_to :my_detail, dependent: :destroy
	  

	def invname
		if form_detail && client.any?
			"00#{form_detail.number}, #{form_detail.date.strftime("%d %b %Y")}, #{clients.first.client_name}, #{services.first.date.strftime("%d %b")} - #{services.last.date.strftime("%d %b")}, #{services.first.service}"
		else 
			'Temporary Invoice Name'
		end
	end 


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

	http_basic_authenticate_with name: "p", password: "secret", except: [:index, :show]

#Create
	def new
		 @invoice = Invoice.new
	end

	def create
 	 	# render text: params[:user_detail].inspect

 	 	@invoice = Invoice.new(invoice_params)
 
  		if @invoice.save
		    redirect_to @invoice
		  else
		    render 'new'
		  end
	end

	def invname 

	end 

#Read

	def index
	  @invoices = Invoice.all
	end

	def show
	 	@invoice = Invoice.find(params[:id])
	 	@client = @invoice.client
	 	@my_detail = @invoice.my_detail

	 	if @my_detail
		 	@bank_detail = @my_detail.bank_detail
		 end
	end

#Update
	def edit
	  @invoice = Invoice.find(params[:id])
	end


	def update
	  @invoice = Invoice.find(params[:id])
	 
	  if @invoice.update(invoice_params) 
		   redirect_to @invoice
	  else
	    render 'edit'
	  end
	end


#Delete
	def destroy
	  @invoice = Invoice.find(params[:id])
	  @invoice.destroy
	 
	  redirect_to invoices_path
	end

#strong params
	private
	  def invoice_params
	    params.require(:invoice).permit(:note)
	  end

 
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<!-- User details -| to be abstracted as separate -->

<%= form_for :invoice, url: invoices_path do |f| %>
  
  <!-- error validation display -->
<% if @invoice.errors.any? %>
 	<div id="errorExplanation">
 		<h2><%= pluralize(@invoice.errors.count, "error") %> prohibited
      this post from being saved:</h2>
      <ul>
    	<% @invoice.errors.full_messages.each do |msg| %>
     	 <li><%= msg %></li>
    	<% end %>
  	  </ul>
 	 </div>
  <% end %>
<!-- end error validation display -->



    <p>
      <%= f.label :note %><br>
      <%= f.text_area :note %>
    </p>

   <p>
       <%= f.submit :class => "btn" %>
    </p>
<% end %>

app/views/invoices/edit.html.erb
<h3>Editing Invoice Note</h3>
 
<%= form_for :invoice, url: invoice_path(@invoice.id),
method: :patch do |f| %>

 <!-- error validation display -->
<% if @invoice.errors.any? %>
 	<div id="errorExplanation">
 		<h2><%= pluralize(@invoice.errors.count, "error") %> prohibited
      this post from being saved:</h2>
      <ul>
    	<% @invoice.errors.full_messages.each do |msg| %>
     	 <li><%= msg %></li>
    	<% end %>
  	  </ul>
 	 </div>
  <% end %>
<!-- end error validation display -->

    <p>
      <%= f.label :notes %>
      <%= f.text_field :note %>
    </p>


    <p>
       <%= f.submit :class => "btn" %>
    </p>
<% end %>

<!-- End User details -->

app/views/invoices/index.html.erb
<h1>Listing Invoices</h1>

<p><%= Time.now.strftime("%d %b %Y - %H :%M") %> </p>
 
<table  class="table table-hover">
   <thead>
  <tr>
    <th>Invoice Name</th>
    <th>Notes</th>
  
    <th>Delete</th>
  </tr>
 </thead>
 <tbody>
  <% @invoices.each do |invoice| %>
    <tr>
      <td><%= link_to invoice, invoice_path(invoice) %></td>
     <td><%= link_to invoice.note, edit_invoice_path(invoice) %></td>
     <td><%= link_to 'Delete', invoice_path(invoice),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

<br>
<%= link_to 'New Invoice', new_invoice_path %>   
<!--delete it, just keep, edit user details -->

app/views/invoices/new.html.erb
<h2>New invoice</h2>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<!-- is this not the same as index? -->

<div class="well well-lg">
<div class="container">


<h1>Invoice</h1>


	<div class="row-fluid">
		<div class="span12">
			<div class="span1">	</div>
			<div class="span7">
<!-- form details -->
			  <%= render @invoice.form_detail if @invoice.form_detail  %></br>
<!-- client details -->
				  <%= render "clients/client" %>
			</div>
		
			<div class="span3">
<!-- invoice my details  -->
				<%= render @invoice.my_detail if @invoice.my_detail %> 


<!-- 	trying out with new my detail form link -->
	<%= link_to 'New My Detail', new_invoice_my_detail_path([@invoice, @my_detail]) %>


			</div>
		</div>

	<div class="span12">
		<div class="span12"></div>
			<div class="span2"></div>
			<div class="span6">
<!-- service description -->
				<p>Providing <%= @invoice.services.first.service if @invoice.services.any? %> services as follow: </p>
				

<!-- Services list -->
<table  class="table table-hover"   data-provides="rowlink">
   <thead>
      <tr>
        <th><strong>Date</strong></th>
        <th><strong>Services</strong></th>
        <th><strong>Rate</strong></th>
        <th></th>
        <th></th>    
      </tr>
  </thead>
 <tbody>
 	<% for service in @invoice.services %>
 	<tr>
      <td><%= service.date %></td>
      <td><%= service.service %>  </td>
      <td><%= service.rate %> £ </td> 
      <td><%=  %> </td>
      <td><%= link_to 'Delete', [service.invoice, service],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>  
    <% end %>
    </tr>
	<tr>
		<td></td>
		<td></td>
		<td><p><b><%= @invoice.services.sum('rate') %> £</b></p></td>
		<td></td>
		<td></td>
	 </tr>
  </tbody>
</table>
<!-- end of services -->



</div>
<div class="span2">
			</div>
		<div class="span12">
		</div>
		<div class="span12">
		</div>
			<div class="span1">
			</div>
			<div class="span6">
				<p>Payment terms: 21 days net.<br><br>Payment Details:</p>
<!-- Bank  details-->
			<%= render @bank_detail if @bank_detail %>
			</div>
			<div class="span3">
			</div>
		</div>
	</div>
</div>


<!-- note -->
	<strong>Note: </strong><%= @invoice.note %>
<!-- edit note -->
	<%= link_to 'Edit', edit_invoice_path(@invoice) %> 
</div>
<!-- back link-->
	<%= link_to 'Back', invoices_path %> </br>




<!-- ---delete below here when done ------------------- -->

<div class="well well-lg">
<div class="container">

<h1>Invoice</h1>
	<div class="row-fluid">
		<div class="span12">
			<div class="span1">
			</div>
			<div class="span7">
<!-- Invoice Form details -->
			   <% render "form_details/form" unless @invoice.form_detail %>
			</br>
<!-- client form -->
			  <%= render "clients/form" %>
			</div>
		
			<div class="span3">
<!-- my details form -->
				<%# render "my_details/form" %>
			</div>
		</div>



		<div class="span12">
			<div class="span12"></div>
			<div class="span2"></div>
			<div class="span6">

<!-- services form -->
			<%# render "services/form" %>
			</div>
			<div class="span2"></div>
			<div class="span12"></div>
			<div class="span12"></div>
			<div class="span1"></div>
			<div class="span6">
				<p>Payment terms: 21 days net</br>Payment Details:</p>
<!-- Bank -->
			<%# render "bank_details/form" %>
			</div>
			<div class="span3"></div>
		</div>
	</div>
</div>