config/routes.rb
Invoiceapp::Application.routes.draw do

  get "welcome/index"

   
  resources :invoices do 
   resource :form_detail
   resource :service
   resources :my_details
   resource :bank_detail
   resources :clients
end 

      
   
  

  root 'welcome#index'

  

end

app/models/my_detail.rb
class MyDetail < ActiveRecord::Base
 has_one :bank_account
 has_many :invoices
end

app/controllers/my_details_controller.rb
class MyDetailsController < ApplicationController
	http_basic_authenticate_with name: "p", password: "secret", only: :destroy
	def new
    my_detail = MyDetail.new
  end 
  def create
	    @invoice = Invoice.find(params[:invoice_id])
	    @my_detail = @invoice.my_details.create(params[:my_detail].permit(:name, :address, :phone, :email))
	    redirect_to invoice_path(@invoice)
  end

  def destroy
    @invoice = Invoice.find(params[:invoice_id])
    @my_detail = @invoice.my_details.find(params[:id])
    @my_detail.destroy
    redirect_to invoice_path(@invoice)
  end
 


#Update
  def edit
  @my_detail = my_detail.find(params[:id])
  @invoice = Invoice.find(params[:invoice_id])
end

  def update
    @invoice = Invoice.find(params[:invoice_id])
    @my_detail = MyDetail.find(params[:id])

    if
      @my_detail.update_attributes(params[:my_detail])
      redirect_to @invoice
    else
      render 'edit'
    end
    
  end

  def show
  @invoice = Invoice.find(params[:id])
  @my_detail = @invoice.my_details.build
end

#strong params
  private
    def my_detail_params
      params.require(:my_detail).permit(:name, :address, :phone, :email)
    end



end

app/helpers/my_details_helper.rb
module MyDetailsHelper
end

app/views/my_details/_form.html.erb
<h3>My Details</h3>
<%= form_for([@invoice, @invoice.my_details.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
   <p>
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit :class => "btn" %>
  </p>
<% end %>

app/views/my_details/_my_detail.html.erb
  <p>
    <strong>Name:</strong>
    <%= my_detail.name %>
  </p> 
  <p>
    <strong>Date:</strong>
    <%= my_detail.address %>
  </p>
   <strong>Phone:</strong>
    <%= my_detail.phone %>
  </p>

    </p>
   <strong>e-mail:</strong>
    <%= my_detail.email %>
  </p>

<p>
  <%= link_to 'Delete My Details', [my_detail.invoice, my_detail],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/my_details/_show.html.erb
 
<h2>Form Details:</h2>
<%= form_for([@invoice, @invoice.my_details.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
   <p>
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
    <%= f.submit :class => "btn" %>
  </p>
<% end %>
 

app/views/my_details/new.html.erb
<h2>New invoice</h2>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>